### ISSUE TITLE
Download the Coder binary to the workflow workspace folder

### ISSUE THREAD

**Issue by Marketos-Damigos** [coder/setup-action#2]
Currently the action tries to run download the coder binary and store it in `/usr/local/bin/coder` which requires the runner to run with root priviledges. In some systems that might not be possible (either very strict IT policies, or very closed down environment). 

Suggestion: Could we change the path to the path of the workflow workspace (where the runner should have permissions).

```
runs:
  using: "composite"
  steps:
    - name: Download Coder binary from access URL
      run: curl -fsSL $CODER_URL/bin/coder-linux-amd64 -o /usr/local/bin/coder && chmod +x /usr/local/bin/coder
      shell: bash
      env:
        CODER_URL: ${{ inputs.access_url }}
```
